name = "harvey-analytics-api"
main = "src/index.js"
compatibility_date = "2026-08-02"

[vars]
ALLOWED_ORIGIN = "https://theharveyeffect.com"
STRIPE_SERVICE_PRICES = '{"short-form-editing:short-form-edit":"price_1U3nSPEUt9h2ALU66F6k2cZC","long-form-editing:long-form-edit":"price_1U3nwlEUt9h2ALU6fL4A8Ntv","show-producing:show-produced":"price_1U3nyREUt9h2ALU6EUwlJ0A7","motion-graphics:visual-identity-system":"price_1U3o3zEUt9h2ALU6zhJhMF1C","motion-graphics:2d-opener":"price_1U3o6bEUt9h2ALU6dMs3l44h","motion-graphics:lower-third-mogrt":"price_1U3o97EUt9h2ALU6Y6OuKUcW","motion-graphics:2d-transition":"price_1U3oDOEUt9h2ALU6yc6cQr7G"}'
STRIPE_SUCCESS_URL = "https://theharveyeffect.com/?checkout=success"
STRIPE_CANCEL_URL = "https://theharveyeffect.com/?checkout=cancelled"

[[d1_databases]]
binding = "DB"
database_name = "harvey-analytics"
database_id = "8bcfdaee-957a-4b38-8bc6-e4d8c0d33f39"
